from pathlib import Path
import subprocess


def replace(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text(encoding="utf-8")
    if old not in text:
        raise SystemExit(f"expected text not found in {path}: {old[:200]!r}")
    p.write_text(text.replace(old, new, 1), encoding="utf-8")

p = "src/events.rs"
replace(
    p,
    '''    /// Whether `other` denotes the same media item as `self` for the\n    /// update-vs-new-pill decision: same source, title and artist, and no\n    /// contradicting artwork. A different cover (both sides present)\n    /// identifies different media (e.g. a video vs audio version of the same\n    /// song); missing artwork on either side — SMTC fills the thumbnail a\n    /// moment after the title — is tolerated as the same item so the pill\n    /// updates in place instead of re-notifying. With no artwork on either\n    /// side, an equal-or-unknown duration is required, so two recordings can\n    /// still be told apart.\n    pub fn same_media(&self, other: &TrackInfo) -> bool {\n        self.source_app == other.source_app\n            && self.title == other.title\n            && self.artist == other.artist\n            && match (&self.artwork, &other.artwork) {\n                (Some(_), Some(_)) => artwork_same(self.artwork.as_deref(), other.artwork.as_deref()),\n                (None, Some(_)) | (Some(_), None) => true,\n                (None, None) => {\n                    self.duration_secs == other.duration_secs\n                        || self.duration_secs.is_none()\n                        || other.duration_secs.is_none()\n                }\n            }\n    }\n''',
    '''    /// Whether `other` denotes the same logical media item as `self` for\n    /// update-vs-new-pill/history decisions. Title/artist alone are not enough:\n    /// sources can legitimately play two items with the same labels. Artwork is\n    /// also not a complete identity because SMTC commonly reports it one read\n    /// late (or omits it on metadata-only polls).\n    ///\n    /// Therefore every *known on both sides* identity discriminator must agree\n    /// before a one-sided/missing-art snapshot may merge: duration, track\n    /// number/count, album/subtitle/album-artist, playback type, and artwork\n    /// generation. Unknown/late fields remain compatible, preserving the normal\n    /// title-first -> artwork-later refresh. When both covers exist, their bytes\n    /// must also agree. This keeps enrichment in place while a contradictory\n    /// same-title transition is always treated as new media.\n    pub fn same_media(&self, other: &TrackInfo) -> bool {\n        fn known_eq<T: PartialEq>(a: Option<&T>, b: Option<&T>) -> bool {\n            a.zip(b).is_none_or(|(a, b)| a == b)\n        }\n        fn known_text_eq(a: &str, b: &str) -> bool {\n            a.trim().is_empty() || b.trim().is_empty() || a == b\n        }\n\n        let playback_type_compatible = self.playback_type == PlaybackType::Unknown\n            || other.playback_type == PlaybackType::Unknown\n            || self.playback_type == other.playback_type;\n        let art_generation_compatible = self.art_generation == 0\n            || other.art_generation == 0\n            || self.art_generation == other.art_generation;\n        let metadata_compatible = known_eq(self.duration_secs.as_ref(), other.duration_secs.as_ref())\n            && known_eq(self.track_number.as_ref(), other.track_number.as_ref())\n            && known_eq(self.track_count.as_ref(), other.track_count.as_ref())\n            && known_text_eq(&self.album, &other.album)\n            && known_text_eq(&self.subtitle, &other.subtitle)\n            && known_text_eq(&self.album_artist, &other.album_artist)\n            && playback_type_compatible\n            && art_generation_compatible;\n\n        self.source_app == other.source_app\n            && self.title == other.title\n            && self.artist == other.artist\n            && metadata_compatible\n            && match (&self.artwork, &other.artwork) {\n                (Some(_), Some(_)) => artwork_same(self.artwork.as_deref(), other.artwork.as_deref()),\n                _ => true,\n            }\n    }\n''',
)
replace(
    p,
    '''    #[test]\n    fn same_media_tolerates_late_or_lost_artwork() {\n        // SMTC fills the thumbnail a moment after the title: gaining art for\n        // the same track must stay an in-place update, not a new pill.\n        let no_art = track("Love Me Not", "Ravyn Lenae");\n        let with_art = TrackInfo {\n            artwork: art(b"cover"),\n            ..no_art.clone()\n        };\n        assert!(no_art.same_media(&with_art));\n        assert!(with_art.same_media(&no_art));\n    }\n''',
    '''    #[test]\n    fn same_media_tolerates_late_or_poll_missing_artwork_without_contradiction() {\n        // SMTC fills the thumbnail a moment after the title, and metadata-only\n        // safety polls do not read artwork at all. Either direction remains an\n        // in-place refresh when all known identity metadata agrees.\n        let no_art = TrackInfo {\n            duration_secs: Some(218),\n            album: "Hypnos".into(),\n            ..track("Love Me Not", "Ravyn Lenae")\n        };\n        let with_art = TrackInfo {\n            artwork: art(b"cover"),\n            art_generation: 1,\n            ..no_art.clone()\n        };\n        assert!(no_art.same_media(&with_art));\n        assert!(with_art.same_media(&no_art));\n    }\n\n    #[test]\n    fn same_title_transition_with_missing_art_is_new_media_when_identity_conflicts() {\n        // Regression: the old one-sided-art rule returned true immediately and\n        // swallowed a real transition whenever the new thumbnail had not arrived\n        // yet. Strong metadata disagreement must win over artwork absence.\n        let old = TrackInfo {\n            artwork: art(b"old-cover"),\n            duration_secs: Some(180),\n            track_number: Some(1),\n            track_count: Some(12),\n            album: "First release".into(),\n            playback_type: PlaybackType::Music,\n            art_generation: 4,\n            ..track("Same Name", "Same Artist")\n        };\n        let incoming = TrackInfo {\n            artwork: None,\n            duration_secs: Some(240),\n            track_number: Some(2),\n            track_count: Some(12),\n            album: "Second release".into(),\n            playback_type: PlaybackType::Video,\n            ..track("Same Name", "Same Artist")\n        };\n        assert!(!old.same_media(&incoming));\n        assert!(!incoming.same_media(&old));\n    }\n''',
)
replace(
    p,
    '''        assert!(a.same_media(&shorter), "unknown duration matches anything");\n''',
    '''        assert!(a.same_media(&shorter), "unknown duration remains compatible with a later known value");\n''',
)

subprocess.run(["cargo", "fmt", "--all"], check=True)
subprocess.run(["git", "config", "user.name", "github-actions[bot]"], check=True)
subprocess.run(["git", "config", "user.email", "41898282+github-actions[bot]@users.noreply.github.com"], check=True)
subprocess.run(["git", "add", p], check=True)
subprocess.run(["git", "commit", "-m", "fix(media): distinguish refreshes from real track transitions"], check=True)
subprocess.run(["git", "push", "origin", "HEAD:checkpoint"], check=True)
